name: "Microsoft Security DevOps Scan"

on:
  workflow_dispatch:  # Keep manual trigger
  push:
    branches: [ main ]
    paths:
      - '**/*.go'      # Only run on Go file changes
      - '**/*.yaml'    # Run on YAML file changes (for IaC)
      - '**/*.yml'     # Run on YML file changes
      - '**/*.tf'      # Run on Terraform file changes
      - '**/*.json'    # Run on JSON file changes
      - 'go.mod'       # Run on dependency changes
      - 'go.sum'
      - 'Dockerfile'   # Run on container changes
      - '.github/workflows/ossar.yml'  # Run when this workflow changes
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.go'      # Only run on Go file changes
      - '**/*.yaml'    # Run on YAML file changes (for IaC)
      - '**/*.yml'     # Run on YML file changes
      - '**/*.tf'      # Run on Terraform file changes
      - '**/*.json'    # Run on JSON file changes
      - 'go.mod'       # Run on dependency changes
      - 'go.sum'
      - 'Dockerfile'   # Run on container changes
      - '.github/workflows/ossar.yml'  # Run when this workflow changes
  schedule:
    - cron: '0 0 * * 0'  # Keep weekly runs for full scans

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run the Microsoft Security DevOps (MSDO) action
      - name: Run Microsoft Security DevOps Scan
        uses: microsoft/security-devops-action@v1
        id: msdo
        with:
          # Specify only Linux-compatible tools
          tools: trivy,checkov,terrascan
          # Specify categories to focus the scan
          categories: code,IaC,containers

      # Upload alerts to Security tab
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        if: github.event_name == 'pull_request'
        with:
          fail-on-severity: high

      # Always upload scan results as an artifact for review
      - name: Upload Scan Results
        if: always() && steps.msdo.outputs.sarifFile != ''
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: ${{ steps.msdo.outputs.sarifFile }}
          retention-days: 60 